# Generated by Django 5.0.3 on 2024-03-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEst', models.CharField(max_length=200)),
                ('apellidoEst', models.CharField(max_length=200)),
                ('edadEst', models.IntegerField()),
                ('notaEst', models.IntegerField()),
            ],
        ),
    ]
