# Generated by Django 5.0.3 on 2024-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
