# Generated by Django 5.0.3 on 2024-03-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_producto_categoria_producto_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
