# Generated by Django 5.0.3 on 2024-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_remove_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='default', max_length=100, verbose_name='CAT'),
        ),
    ]
